name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install Dependencies
        run: flutter pub get

      - name: Build for Web
        run: flutter build web --dart-define=OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}

      - name: Set base href for GitHub Pages
        run: |
          # Extract only the repository name from github.repository
          REPO_NAME=$(echo "${{ github.repository }}" | cut -d'/' -f2)
          BASE_HREF="/${REPO_NAME}"
          sed -i "s|<base href=\"/\">|<base href=\"$BASE_HREF/\">|g" build/web/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.MY_GITHUB_PAT }}
          publish_dir: build/web
          target_branch: gh-pages
