name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on pushes to main

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: false  # Disable cache to ensure fresh build

      - name: Install Dependencies
        run: flutter pub get

      - name: Clean Flutter 
        run: flutter clean

      - name: Build for Web
        run: flutter build web

      - name: Hardcode base href for GitHub Pages
        run: |
          # Hardcode the base href to the repository name
          BASE_HREF="/tango_ai_companion/"
          echo "Setting base href to: $BASE_HREF"
          # Update the base href in the index.html file to the hardcoded value
          sed -i "s|<base href=\"/\">|<base href=\"$BASE_HREF\">|g" build/web/index.html
          
      - name: Create 404.html for SPA routing
        run: |
          # Create a 404.html that redirects to index.html with the original path
          cat > build/web/404.html << 'EOL'
          <!DOCTYPE html>
          <html>
            <head>
              <meta charset="utf-8">
              <title>Tango AI Companion</title>
              <script type="text/javascript">
                // Improved SPA routing for GitHub Pages with complex URLs
                // Modified from https://github.com/rafgraph/spa-github-pages
                (function() {
                  var pathSegmentsToKeep = 1; // Keep /tango_ai_companion
                  var fullPath = window.location.pathname;
                  var pathParts = fullPath.split('/').filter(p => p);
                  
                  // Keep the base path (repository name)
                  var basePath = '';
                  if (pathParts.length > 0) {
                    basePath = '/' + pathParts[0];
                  }
                  
                  // Extract the route part (everything after the base path)
                  var routePath = '';
                  if (pathParts.length > 1) {
                    routePath = '/' + pathParts.slice(1).join('/');
                  }
                  
                  // Get any query parameters
                  var queryParams = window.location.search || '';
                  // Get any hash fragment
                  var hashFragment = window.location.hash || '';
                  
                  // Log for debugging
                  console.log('404 Redirect -', {
                    fullPath: fullPath,
                    basePath: basePath,
                    routePath: routePath,
                    queryParams: queryParams
                  });
                  
                  // Redirect to the base URL with the route path as a query parameter
                  window.location.href = basePath + '/?' + 
                    'route=' + encodeURIComponent(routePath) + 
                    (queryParams ? '&' + queryParams.substring(1) : '') + 
                    hashFragment;
                })();
              </script>
            </head>
            <body>
              <p>Redirecting to main page...</p>
            </body>
          </html>
          EOL
          
      - name: Update index.html for SPA routing
        run: |
          # Add SPA route handling script to index.html
          sed -i '/<head>/a \
          <!-- Start Improved SPA routing for GitHub Pages -->\
          <script type="text/javascript">\
            // Process the URL parameters for SPA routing\
            document.addEventListener("DOMContentLoaded", function() {\
              // Function to parse query parameters\
              function getQueryParams() {\
                var params = {};\
                var queryString = window.location.search.substring(1);\
                var pairs = queryString.split("&");\
                for (var i = 0; i < pairs.length; i++) {\
                  var pair = pairs[i].split("=");\
                  if (pair.length === 2) {\
                    params[decodeURIComponent(pair[0])] = decodeURIComponent(pair[1] || "");\
                  }\
                }\
                return params;\
              }\
              \
              var params = getQueryParams();\
              \
              // Check if we have a route parameter from the 404.html redirect\
              if (params.route) {\
                var routePath = params.route;\
                delete params.route;\
                \
                // Rebuild the query string without the route parameter\
                var newQueryString = Object.keys(params)\
                  .map(function(key) { return key + "=" + encodeURIComponent(params[key]); })\
                  .join("&");\
                \
                // Construct the new URL\
                var newPath = window.location.pathname + routePath;\
                var newUrl = newPath + (newQueryString ? "?" + newQueryString : "") + window.location.hash;\
                \
                console.log("Redirecting to:", newUrl);\
                \
                // Use replaceState to update the URL without reloading\
                if (window.history && window.history.replaceState) {\
                  window.history.replaceState(null, null, newUrl);\
                }\
              }\
            });\
          </script>\
          <!-- End Improved SPA routing for GitHub Pages -->' build/web/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'build/web'
          
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
